---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: attendance-storage
  namespace: university-backend
  labels:
    app: attendance-service
    component: backend

spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
