---
apiVersion: v1
kind: Namespace
metadata:
  name: university-frontend
  labels:
    app.kubernetes.io/name: kubevision
    app.kubernetes.io/tier: frontend

---
apiVersion: v1
kind: Namespace
metadata:
  name: university-backend
  labels:
    app.kubernetes.io/name: kubevision
    app.kubernetes.io/tier: backend

---
apiVersion: v1
kind: Namespace
metadata:
  name: university-data
  labels:
    app.kubernetes.io/name: kubevision
    app.kubernetes.io/tier: data

---
apiVersion: v1
kind: Namespace
metadata:
  name: kubevision
  labels:
    app.kubernetes.io/name: kubevision
